"""
core/slam_validator.py — ORBSLAM3 / evo trajectory validation.

Runs ORBSLAM3 as a subprocess on EuRoC-format extracted sessions,
parses TUM-format trajectory files, computes drift metrics, and
aligns SLAM trajectories with GPS ground truth via Umeyama alignment.

No UI imports — pure Python business logic.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Callable

import numpy as np
from loguru import logger

from core.models import (
    CalibrationResult,
    GPSSample,
    SLAMResult,
    TrajectoryMetrics,
    TrajectoryPoint,
)

ProgressCB = Callable[[int], None]
StatusCB = Callable[[str], None]

_TUM_HEADER = "# timestamp tx ty tz qx qy qz qw"


# ---------------------------------------------------------------------------
# Installation checks
# ---------------------------------------------------------------------------

def check_slam_installation() -> dict:
    """Check availability of ORBSLAM3, VINS-Mono (ROS), and evo.

    Returns:
        dict with keys: orbslam3, vins_mono, evo — each with sub-fields.
    """
    orbslam3_path = shutil.which("ORBSLAM3") or shutil.which("orbslam3")

    try:
        import evo  # noqa: F401
        evo_installed = True
    except ImportError:
        evo_installed = False

    ros_available = bool(shutil.which("roscore"))

    return {
        "orbslam3": {
            "installed": orbslam3_path is not None,
            "path": orbslam3_path,
        },
        "vins_mono": {
            "installed": False,  # Requires ROS and vins_mono_node
            "ros_available": ros_available,
        },
        "evo": {
            "installed": evo_installed,
        },
    }


# ---------------------------------------------------------------------------
# ORBSLAM3 config generation
# ---------------------------------------------------------------------------

def generate_orbslam3_config(
    calibration_result: CalibrationResult,
    session_fps: float,
    imu_rate_hz: float,
    output_path: str,
) -> str:
    """Generate an ORBSLAM3 YAML config from a CalibrationResult.

    Args:
        calibration_result: From core/calibration.py output.
        session_fps:        Video frame rate of the recording.
        imu_rate_hz:        IMU sampling rate in Hz.
        output_path:        Path to write the YAML file.

    Returns:
        Absolute path to the written YAML file.

    Raises:
        ValueError: if calibration_result is missing intrinsic parameters.
    """
    if not calibration_result.fx or not calibration_result.fy:
        raise ValueError(
            "CalibrationResult is missing intrinsic parameters (fx/fy). "
            "Complete camera intrinsic calibration (Step 2) before generating "
            "an ORBSLAM3 config."
        )

    dist = calibration_result.dist_coeffs
    k1 = dist[0] if len(dist) > 0 else 0.0
    k2 = dist[1] if len(dist) > 1 else 0.0
    p1 = dist[2] if len(dist) > 2 else 0.0
    p2 = dist[3] if len(dist) > 3 else 0.0

    # IMU noise params (defaults if not calibrated)
    noise = calibration_result.imu_noise_params
    gyro_noise   = noise.get("gyro_noise_density",  0.005)
    accel_noise  = noise.get("accel_noise_density", 0.01)
    gyro_walk    = noise.get("gyro_random_walk",    4e-6)
    accel_walk   = noise.get("accel_random_walk",   2e-4)

    yaml_content = f"""%YAML:1.0

#--------------------------------------------------------------------------------------------
# Auto-generated by RoverDataKit from CalibrationResult
# Session: {calibration_result.session_id}
#--------------------------------------------------------------------------------------------

Camera.type: "PinHole"

# Camera calibration and distortion parameters
Camera.fx: {calibration_result.fx:.6f}
Camera.fy: {calibration_result.fy:.6f}
Camera.cx: {calibration_result.cx:.6f}
Camera.cy: {calibration_result.cy:.6f}
Camera.k1: {k1:.8f}
Camera.k2: {k2:.8f}
Camera.p1: {p1:.8f}
Camera.p2: {p2:.8f}

# Camera frames per second
Camera.fps: {session_fps:.1f}

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to IMU (T_imu_cam), if using mono-inertial mode
# Fill from CalibrationResult.T_cam_imu (T_cam_imu is the inverse of T_imu_cam)
# Example 4x4 identity if not calibrated:
IMU.T_b_c1:
 [1.0, 0.0, 0.0, 0.0,
  0.0, 1.0, 0.0, 0.0,
  0.0, 0.0, 1.0, 0.0,
  0.0, 0.0, 0.0, 1.0]

# IMU noise parameters
IMU.NoiseGyro: {gyro_noise:.8f}
IMU.NoiseAcc:  {accel_noise:.8f}
IMU.GyroWalk:  {gyro_walk:.2e}
IMU.AccWalk:   {accel_walk:.2e}
IMU.Frequency: {imu_rate_hz:.1f}

# ORB Extractor
ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# Viewer
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
"""

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml_content)
    logger.info("slam_validator: ORBSLAM3 config written to {}", out)
    return str(out.resolve())


# ---------------------------------------------------------------------------
# ORBSLAM3 subprocess runner
# ---------------------------------------------------------------------------

def run_orbslam3(
    euroc_session_dir: str,
    vocabulary_path: str,
    config_yaml_path: str,
    mode: str = "mono_inertial",
    progress_callback: ProgressCB | None = None,
    status_callback: StatusCB | None = None,
) -> SLAMResult:
    """Run ORBSLAM3 on a EuRoC-format session.

    The ORBSLAM3 binary writes CameraTrajectory.txt and
    KeyFrameTrajectory.txt in TUM format to the current working directory.

    Args:
        euroc_session_dir: Path to EuRoC session (must have cam0/ and imu0/).
        vocabulary_path:   Path to ORB vocabulary file (ORBvoc.txt).
        config_yaml_path:  Path to ORBSLAM3 YAML config.
        mode:              "mono", "mono_inertial", "stereo", "stereo_inertial".
        progress_callback: 0-100.
        status_callback:   Called with each stdout line from ORBSLAM3.

    Returns:
        SLAMResult with parsed trajectory and metrics.

    Raises:
        FileNotFoundError: if ORBSLAM3 binary not found.
        RuntimeError: if ORBSLAM3 exits with non-zero code.
    """
    session_id = Path(euroc_session_dir).name

    # Validate EuRoC structure
    session_path = Path(euroc_session_dir)
    cam0_dir = session_path / "cam0" / "data"
    imu_csv = session_path / "imu0" / "data.csv"
    if not cam0_dir.exists():
        raise FileNotFoundError(
            f"EuRoC cam0/data/ directory not found in {euroc_session_dir}. "
            "Run extraction with EuRoC output format first."
        )

    orbslam3_bin = shutil.which("ORBSLAM3") or shutil.which("orbslam3")
    if not orbslam3_bin:
        raise FileNotFoundError(
            "ORBSLAM3 binary not found on PATH. "
            "Install ORBSLAM3 and add it to your PATH, "
            "or configure the binary path in Settings."
        )

    if not Path(vocabulary_path).exists():
        raise FileNotFoundError(
            f"ORB vocabulary file not found: {vocabulary_path}. "
            "Download ORBvoc.txt from the ORBSLAM3 repository."
        )

    if not Path(config_yaml_path).exists():
        raise FileNotFoundError(
            f"ORBSLAM3 YAML config not found: {config_yaml_path}. "
            "Generate it via 'Auto-gen config from calibration' button, "
            "or provide a manually created YAML."
        )

    mode_map = {
        "mono":             "Monocular",
        "mono_inertial":    "Mono_Inertial",
        "stereo":           "Stereo",
        "stereo_inertial":  "Stereo_Inertial",
    }
    orbslam_mode = mode_map.get(mode)
    if not orbslam_mode:
        raise ValueError(
            f"Unknown SLAM mode '{mode}'. "
            f"Choose one of: {list(mode_map.keys())}"
        )

    cmd = [
        orbslam3_bin,
        orbslam_mode,
        vocabulary_path,
        config_yaml_path,
        euroc_session_dir,
    ]

    logger.info("slam_validator: running ORBSLAM3: {}", " ".join(cmd))
    tracking_log: list[str] = []

    import os as _os
    from core.reconstructor import _clean_snap_env
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        cwd=str(session_path),  # trajectory files written here
        env=_clean_snap_env(_os.environ.copy()),
    )

    keyframes = 0
    map_points = 0
    tracking_lost_count = 0

    try:
        for line in proc.stdout:  # type: ignore[union-attr]
            line = line.rstrip()
            tracking_log.append(line)
            if status_callback:
                status_callback(line)

            # Parse progress indicators
            if "Tracking LOST" in line or "LOST" in line.upper():
                tracking_lost_count += 1
            if "KFs in map:" in line:
                try:
                    keyframes = int(line.split("KFs in map:")[1].strip().split()[0])
                except (ValueError, IndexError):
                    pass
            if "MPs in map:" in line:
                try:
                    map_points = int(line.split("MPs in map:")[1].strip().split()[0])
                except (ValueError, IndexError):
                    pass

        proc.wait()
    except Exception as exc:
        proc.kill()
        raise RuntimeError(
            f"ORBSLAM3 subprocess failed: {exc}"
        ) from exc

    if proc.returncode != 0:
        return SLAMResult(
            session_id=session_id,
            mode=mode,
            trajectory=[],
            metrics=TrajectoryMetrics(
                total_distance_m=0.0,
                duration_seconds=0.0,
                avg_speed_mps=0.0,
                tracking_lost_count=tracking_lost_count,
                keyframe_count=keyframes,
                map_point_count=map_points,
            ),
            config_used=config_yaml_path,
            tracking_log=tracking_log[-200:],  # keep last 200 lines
            success=False,
            failure_reason=(
                f"ORBSLAM3 exited with code {proc.returncode}. "
                "Check the log for tracking failures. "
                "Common causes: poor lighting, fast motion, or incorrect calibration."
            ),
        )

    # Parse trajectory
    traj_file = session_path / "CameraTrajectory.txt"
    kf_file   = session_path / "KeyFrameTrajectory.txt"
    traj_path = kf_file if kf_file.exists() else traj_file

    if not traj_path.exists():
        raise RuntimeError(
            f"ORBSLAM3 did not produce a trajectory file at {traj_path}. "
            "Check the tracking log — tracking may have failed immediately."
        )

    trajectory = _parse_tum_trajectory(str(traj_path))
    metrics = compute_trajectory_metrics(trajectory)
    metrics = TrajectoryMetrics(
        **{
            **metrics.model_dump(),
            "tracking_lost_count": tracking_lost_count,
            "keyframe_count": keyframes,
            "map_point_count": map_points,
        }
    )

    logger.info(
        "slam_validator: ORBSLAM3 done — {} trajectory points, drift={:.2f}m",
        len(trajectory),
        metrics.loop_closure_drift_m or 0.0,
    )
    return SLAMResult(
        session_id=session_id,
        mode=mode,
        trajectory=trajectory,
        metrics=metrics,
        config_used=config_yaml_path,
        tracking_log=tracking_log[-200:],
        success=True,
        failure_reason=None,
    )


# ---------------------------------------------------------------------------
# Trajectory parsing
# ---------------------------------------------------------------------------

def _parse_tum_trajectory(tum_path: str) -> list[TrajectoryPoint]:
    """Parse a TUM-format trajectory file into TrajectoryPoint list.

    TUM format: timestamp tx ty tz qx qy qz qw (space-separated, seconds)
    """
    points: list[TrajectoryPoint] = []
    path = Path(tum_path)
    if not path.exists():
        return points

    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 8:
                continue
            try:
                ts_s = float(parts[0])
                points.append(
                    TrajectoryPoint(
                        timestamp_ns=int(ts_s * 1e9),
                        tx=float(parts[1]),
                        ty=float(parts[2]),
                        tz=float(parts[3]),
                        qx=float(parts[4]),
                        qy=float(parts[5]),
                        qz=float(parts[6]),
                        qw=float(parts[7]),
                    )
                )
            except (ValueError, IndexError):
                continue
    return points


# ---------------------------------------------------------------------------
# Trajectory metrics
# ---------------------------------------------------------------------------

def compute_trajectory_metrics(
    trajectory: list[TrajectoryPoint],
    ground_truth: list[TrajectoryPoint] | None = None,
) -> TrajectoryMetrics:
    """Compute distance, drift, and optional ATE/RPE metrics.

    Args:
        trajectory:    Parsed SLAM trajectory.
        ground_truth:  Optional GT trajectory for ATE/RPE.

    Returns:
        TrajectoryMetrics.
    """
    if not trajectory:
        return TrajectoryMetrics(
            total_distance_m=0.0,
            duration_seconds=0.0,
            avg_speed_mps=0.0,
            tracking_lost_count=0,
            keyframe_count=0,
            map_point_count=0,
        )

    positions = np.array([[p.tx, p.ty, p.tz] for p in trajectory])

    # Total distance
    diffs = np.diff(positions, axis=0)
    distances = np.linalg.norm(diffs, axis=1)
    total_dist = float(distances.sum())

    # Duration
    t_start = trajectory[0].timestamp_ns
    t_end   = trajectory[-1].timestamp_ns
    duration = (t_end - t_start) / 1e9
    avg_speed = total_dist / duration if duration > 0 else 0.0

    # Loop closure drift: if start and end are within 5m, treat as loop
    start_pos = positions[0]
    end_pos   = positions[-1]
    end_to_start = float(np.linalg.norm(end_pos - start_pos))
    is_loop = end_to_start < 5.0
    drift_m   = end_to_start if is_loop else None
    drift_pct = (end_to_start / total_dist * 100.0) if (is_loop and total_dist > 0) else None

    # ATE / RPE (requires evo or ground truth)
    ate_rmse = None
    rpe_rmse = None
    if ground_truth:
        ate_rmse = _compute_ate(trajectory, ground_truth)
        rpe_rmse = _compute_rpe(trajectory, ground_truth)

    return TrajectoryMetrics(
        total_distance_m=round(total_dist, 4),
        duration_seconds=round(duration, 3),
        avg_speed_mps=round(avg_speed, 4),
        loop_closure_drift_m=round(drift_m, 4) if drift_m is not None else None,
        loop_closure_drift_percent=round(drift_pct, 2) if drift_pct is not None else None,
        ate_rmse=ate_rmse,
        rpe_rmse=rpe_rmse,
        tracking_lost_count=0,   # filled in by caller
        keyframe_count=0,
        map_point_count=0,
    )


def _compute_ate(
    traj: list[TrajectoryPoint],
    gt: list[TrajectoryPoint],
) -> float:
    """Absolute Trajectory Error RMSE (simplified: nearest-neighbor matching)."""
    est = np.array([[p.tx, p.ty, p.tz] for p in traj])
    ref = np.array([[p.tx, p.ty, p.tz] for p in gt])
    # Match by index, truncate to shorter
    n = min(len(est), len(ref))
    errors = np.linalg.norm(est[:n] - ref[:n], axis=1)
    return float(np.sqrt(np.mean(errors ** 2)))


def _compute_rpe(
    traj: list[TrajectoryPoint],
    gt: list[TrajectoryPoint],
    delta: int = 1,
) -> float:
    """Relative Pose Error RMSE over delta-step pairs."""
    est = np.array([[p.tx, p.ty, p.tz] for p in traj])
    ref = np.array([[p.tx, p.ty, p.tz] for p in gt])
    n = min(len(est), len(ref)) - delta
    if n <= 0:
        return 0.0
    est_rel = est[delta:n + delta] - est[:n]
    ref_rel = ref[delta:n + delta] - ref[:n]
    errors = np.linalg.norm(est_rel - ref_rel, axis=1)
    return float(np.sqrt(np.mean(errors ** 2)))


# ---------------------------------------------------------------------------
# GPS alignment (Umeyama)
# ---------------------------------------------------------------------------

def align_trajectory_with_gps(
    trajectory: list[TrajectoryPoint],
    gps_track: list[GPSSample],
) -> tuple[list[TrajectoryPoint], float]:
    """Align SLAM trajectory scale and orientation with GPS ground truth.

    Uses the Umeyama similarity transform (scale + rotation + translation)
    via numpy SVD.

    Args:
        trajectory: SLAM trajectory in local coordinates.
        gps_track:  GPS samples as reference (lat/lon → local ENU coords).

    Returns:
        (aligned_trajectory, scale_factor) tuple.
    """
    if len(trajectory) < 3 or len(gps_track) < 3:
        logger.warning(
            "slam_validator: not enough points for Umeyama alignment "
            "(need >= 3 trajectory + GPS points)"
        )
        return trajectory, 1.0

    # Convert GPS to local ENU (east-north-up) centred on first point
    ref_lat = gps_track[0].latitude
    ref_lon = gps_track[0].longitude
    gps_enu = _gps_to_enu(gps_track, ref_lat, ref_lon)

    # Subsample to matching length
    n = min(len(trajectory), len(gps_enu))
    src = np.array([[p.tx, p.ty, p.tz] for p in trajectory[:n]])
    dst = gps_enu[:n]

    R, t, scale = _umeyama(src, dst)

    # Apply transform to all trajectory points
    aligned: list[TrajectoryPoint] = []
    for p in trajectory:
        pos = np.array([p.tx, p.ty, p.tz])
        aligned_pos = scale * (R @ pos) + t
        aligned.append(
            TrajectoryPoint(
                timestamp_ns=p.timestamp_ns,
                tx=float(aligned_pos[0]),
                ty=float(aligned_pos[1]),
                tz=float(aligned_pos[2]),
                qx=p.qx, qy=p.qy, qz=p.qz, qw=p.qw,
            )
        )

    logger.info("slam_validator: Umeyama alignment scale = {:.4f}", scale)
    return aligned, float(scale)


def _gps_to_enu(
    gps_samples: list[GPSSample],
    ref_lat: float,
    ref_lon: float,
) -> np.ndarray:
    """Convert GPS lat/lon to local ENU (metres) relative to reference point."""
    R_earth = 6_371_000.0  # metres
    enu: list[list[float]] = []
    for s in gps_samples:
        dlat = s.latitude - ref_lat
        dlon = s.longitude - ref_lon
        e = dlon * R_earth * abs(np.cos(np.radians(ref_lat))) * np.pi / 180.0
        n = dlat * R_earth * np.pi / 180.0
        u = s.altitude_m - gps_samples[0].altitude_m
        enu.append([e, n, u])
    return np.array(enu)


def _umeyama(src: np.ndarray, dst: np.ndarray) -> tuple[np.ndarray, np.ndarray, float]:
    """Umeyama similarity transform: find R, t, scale such that dst ≈ scale * R @ src + t."""
    n = len(src)
    mu_s = src.mean(axis=0)
    mu_d = dst.mean(axis=0)
    src_c = src - mu_s
    dst_c = dst - mu_d

    # Covariance
    A = (dst_c.T @ src_c) / n

    U, S, Vt = np.linalg.svd(A)
    D = np.eye(3)
    D[2, 2] = np.sign(np.linalg.det(U @ Vt))

    R = U @ D @ Vt

    var_src = float(np.var(src_c, axis=0).sum())
    scale = float((S @ D.diagonal()) / var_src) if var_src > 0 else 1.0

    t = mu_d - scale * (R @ mu_s)
    return R, t, scale
